"""
train_tinyml_classifier.py
==========================
Trains a small Keras neural network for 3-class LED bulb status
classification, then converts it to a quantised TensorFlow Lite model
ready for deployment on an ESP32 via EloquentTinyML.

Model architecture
------------------
    Input(6) -> Dense(16, ReLU) -> Dense(8, ReLU) -> Dense(3, Softmax)

The model is intentionally tiny (~2 KB after int8 quantisation) so it
fits comfortably in the ESP32's flash and SRAM.

Input features (computed from a 20-sample sliding window of LDR readings):
    0  ldr_norm          - current LDR reading normalised to 0..1
    1  avg_norm          - window moving-average normalised to 0..1
    2  rate_of_change    - (newest - oldest) / ADC_MAX
    3  variance          - normalised variance of the window
    4  min_norm          - minimum reading in window / ADC_MAX
    5  max_norm          - maximum reading in window / ADC_MAX

Output classes:
    0 = HEALTHY
    1 = DEGRADING
    2 = FAILED

Usage
-----
    C:\\ml_venv\\Scripts\\python.exe train_tinyml_classifier.py

Prerequisites
-------------
    TensorFlow, numpy, pandas, scikit-learn  (install in the venv)

Outputs
-------
    ml/training/models/tinyml_classifier.keras   - saved Keras model
    ml/training/models/bulb_model.tflite         - quantised TFLite model
    ml/training/models/bulb_model.h              - C header for Arduino
    edge-logic/firmware/light_monitor/bulb_model.h - copy for firmware
"""

import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# TensorFlow import (suppress info logs)
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
import tensorflow as tf

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_CSV = os.path.join(SCRIPT_DIR, "data", "tinyml_training_data.csv")
MODEL_DIR = os.path.join(SCRIPT_DIR, "models")
KERAS_PATH = os.path.join(MODEL_DIR, "tinyml_classifier.keras")
TFLITE_PATH = os.path.join(MODEL_DIR, "bulb_model.tflite")
HEADER_PATH = os.path.join(MODEL_DIR, "bulb_model.h")

# ---------------------------------------------------------------------------
# Hyper-parameters
# ---------------------------------------------------------------------------
NUM_FEATURES = 6
NUM_CLASSES = 3
EPOCHS = 50
BATCH_SIZE = 32
VALIDATION_SPLIT = 0.2
RANDOM_STATE = 42

CLASS_NAMES = ["HEALTHY", "DEGRADING", "FAILED"]


def load_data():
    """Load the CSV generated by generate_tinyml_training_data.py."""
    df = pd.read_csv(DATA_CSV)
    X = df.iloc[:, :NUM_FEATURES].values.astype(np.float32)
    y = df["label"].values.astype(np.int32)
    return X, y


def build_model() -> tf.keras.Model:
    """
    Build the tiny classifier.

    Architecture chosen to be small enough for ESP32:
        Dense(16) -> Dense(8) -> Dense(3)
    Total params ~ 200  ->  ~2 KB after int8 quantisation.
    """
    model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(NUM_FEATURES,)),
        tf.keras.layers.Dense(16, activation="relu", name="hidden_1"),
        tf.keras.layers.Dense(8, activation="relu", name="hidden_2"),
        tf.keras.layers.Dense(NUM_CLASSES, activation="softmax", name="output"),
    ])

    model.compile(
        optimizer="adam",
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    return model


def convert_to_tflite(model, X_train):
    """
    Convert the Keras model to an int8-quantised TFLite model.

    Int8 quantisation dramatically reduces model size and is the
    format expected by TensorFlow Lite Micro on the ESP32.
    """
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]

    # Representative dataset for full integer quantisation
    def representative_dataset():
        for i in range(min(500, len(X_train))):
            yield [X_train[i:i + 1]]

    converter.representative_dataset = representative_dataset
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.float32   # keep float input for convenience
    converter.inference_output_type = tf.float32

    tflite_model = converter.convert()
    return tflite_model


def export_c_header(tflite_bytes: bytes, output_path: str):
    """
    Convert TFLite model bytes to a C header file for Arduino inclusion.

    This replicates what `xxd -i model.tflite > model.h` does, but
    works cross-platform (including Windows).
    """
    with open(output_path, "w") as f:
        f.write("// Auto-generated by train_tinyml_classifier.py\n")
        f.write("// TFLite int8-quantised model for LED bulb status classification\n")
        f.write("//\n")
        f.write("// Input  (6 floats): ldr_norm, avg_norm, rate_of_change,\n")
        f.write("//                    variance, min_norm, max_norm\n")
        f.write("// Output (3 floats): P(HEALTHY), P(DEGRADING), P(FAILED)\n\n")
        f.write("#ifndef BULB_MODEL_H\n")
        f.write("#define BULB_MODEL_H\n\n")
        f.write(f"const unsigned int bulb_model_len = {len(tflite_bytes)};\n\n")
        f.write("alignas(8) const unsigned char bulb_model[] = {\n")

        # Write bytes in rows of 12 for readability
        for i in range(0, len(tflite_bytes), 12):
            chunk = tflite_bytes[i:i + 12]
            hex_values = ", ".join(f"0x{b:02x}" for b in chunk)
            if i + 12 < len(tflite_bytes):
                f.write(f"    {hex_values},\n")
            else:
                f.write(f"    {hex_values}\n")

        f.write("};\n\n")
        f.write("#endif // BULB_MODEL_H\n")


def main():
    os.makedirs(MODEL_DIR, exist_ok=True)

    # -----------------------------------------------------------------------
    # 1. Load data
    # -----------------------------------------------------------------------
    print("Loading training data ...")
    X, y = load_data()
    print(f"  Samples: {len(X)}  |  Features: {X.shape[1]}")

    # -----------------------------------------------------------------------
    # 2. Train / test split
    # -----------------------------------------------------------------------
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=VALIDATION_SPLIT, random_state=RANDOM_STATE, stratify=y,
    )
    print(f"  Train: {len(X_train)}  |  Test: {len(X_test)}")

    # -----------------------------------------------------------------------
    # 3. Build and train model
    # -----------------------------------------------------------------------
    print("\nTraining model ...")
    model = build_model()
    model.summary()

    history = model.fit(
        X_train, y_train,
        epochs=EPOCHS,
        batch_size=BATCH_SIZE,
        validation_split=0.1,
        verbose=1,
    )

    # -----------------------------------------------------------------------
    # 4. Evaluate on test set
    # -----------------------------------------------------------------------
    print("\n--- Test Set Evaluation ---")
    loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
    print(f"  Loss: {loss:.4f}  |  Accuracy: {accuracy:.4f}")

    y_pred = model.predict(X_test, verbose=0).argmax(axis=1)
    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=CLASS_NAMES))
    print("Confusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    # -----------------------------------------------------------------------
    # 5. Save Keras model
    # -----------------------------------------------------------------------
    model.save(KERAS_PATH)
    print(f"\nKeras model saved -> {KERAS_PATH}")

    # -----------------------------------------------------------------------
    # 6. Convert to TFLite (int8 quantised)
    # -----------------------------------------------------------------------
    print("Converting to TFLite (int8) ...")
    tflite_model = convert_to_tflite(model, X_train)
    with open(TFLITE_PATH, "wb") as f:
        f.write(tflite_model)
    print(f"  TFLite model: {len(tflite_model)} bytes -> {TFLITE_PATH}")

    # -----------------------------------------------------------------------
    # 7. Export C header for Arduino / EloquentTinyML
    # -----------------------------------------------------------------------
    export_c_header(tflite_model, HEADER_PATH)
    print(f"  C header -> {HEADER_PATH}")

    # Also copy header to the firmware directory for convenience
    firmware_header = os.path.join(
        SCRIPT_DIR, "..", "..", "edge-logic", "firmware",
        "light_monitor", "bulb_model.h",
    )
    os.makedirs(os.path.dirname(firmware_header), exist_ok=True)
    export_c_header(tflite_model, firmware_header)
    print(f"  C header -> {firmware_header}")

    print("\nDone. Model is ready for ESP32 deployment.")


if __name__ == "__main__":
    main()
